sudo: false

language: node_js

services:
  - docker

node_js:
  - '8'

before_install:
  - docker pull macacajs/reliable-mysql
  - docker run --rm --name reliable-mysql -p 13306:3306 -d macacajs/reliable-mysql
  - docker ps -a

install:
  - npm i npminstall && npminstall

script:
  - MYSQL_PORT=13306 npm run ci

after_script:
  - npminstall codecov && codecov
